---
# [ansible apt](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html)
# [ansible shell](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html)
# [ansible systemd](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html)
# [docker install](https://docs.docker.com/engine/install/ubuntu/)
- hosts: '{{ hosts }}'
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: remove old version
      apt:
        state: absent
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc

    - name: remove old /etc/apt/sources.list.d/docker.list
      shell:
        cmd: rm -f /etc/apt/sources.list.d/docker.list

    - name: install dependencies
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker’s official GPG key
      shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: add /etc/apt/sources.list.d/docker.list
      shell:
        cmd: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu `lsb_release -cs` stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: install docker engine
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: enable and start docker service
      systemd:
        name: docker
        state: started
        enabled: yes